version: '3.8'

services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    restart: unless-stopped
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - "8529:8529"
    volumes:
      - arango_data:/var/lib/arangodb3

volumes:
  arango_data:
